### PR TITLE
Fix/7:Add CLI Help Documentation for all commands

### LINKED ISSUE #7: Add CLI Help Documentation for all commands
Add detailed help documentation for the all command to guide users on how to use it.

Tasks:
- Add descriptions, usage examples, and explanations for the all command and its flags.
- Ensure the command is easy to discover via the CLI help system.

Acceptance Criteria:
- Running ```vc-analyze cmd --help``` should display clear and helpful documentation.
- Provide usage examples for both public and private repositories.

### PR DESCRIPTION
**Pull request by Nikhils-179**
What does this PR do?

This PR adds CLI Help Documentation for all commands . 

Fixes #7 

Screenshots:

Screenshot 2024-10-18 at 4 52 59 PM
Screenshot 2024-10-18 at 4 53 19 PM

### CODE REVIEW

**Comment by Nikhils-179** [comment]
Hi @adigulalkari,

On macOS, a warning appears when using the github.com/shirou/gopsutil/disk package:
```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
```

This is due to the cross-platform nature of the gopsutil library, which aims to be compatible with multiple systems. However, this warning does not impact the actual functioning of the CLI application on macOS.
Please let me know if you’re okay with proceeding, despite this minor warning.

**Comment by adigulalkari** [comment]
Hey @Nikhils-179 
I think there is a confusion.. the issue was mainly for documentation.. I required the documentation like the image provided.. not really the implementation of the function..

**Comment by Nikhils-179** [comment]
oh, I see, I looked for the implementation as well, my bad! Do you want me to remove that?

**Comment by adigulalkari** [comment]
Yes..actually this project majorly focuses on version control.. don't think adding hardware details is any beneficial

**Comment by Nikhils-179** [comment]
so basically suming up , the idea is to print all the available options via vc-analyze cmd --help as diplayed in the table without their implementation like this or the picture you have shared. 
Screenshot 2024-10-18 at 4 53 19 PM

**Comment by adigulalkari** [comment]
i need this kind of table for the functions that have been already implemented in vc-analyzer
i.e. 
calc-stats
check-anti-patterns
etc..
with their flags & shorthand

the functions given in the picture were a reference taken from another repo

**Comment by Nikhils-179** [comment]
Ok @adigulalkari  Got it .

**Pull request closed without merging**
